import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HeaderSlot from "@/components/layout/HeaderSlot";
import FooterSlot from "@/components/layout/FooterSlot";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen bg-[#2b1a12] text-neutral-100 grid grid-rows-[auto_minmax(0,1fr)_auto]">
          <HeaderSlot />
          <main className="min-w-0 min-h-0 pt-[var(--topbar-height,0px)]">
            {children}
          </main>
          <FooterSlot />
        </div>
      </body>
    </html>
  );
}
